export default [
    {
        name:'sailesh',
        id:202,
        location:'chennai',
        work:'ITjob',
        car:'Thar'
    },
    {
        name:'sailesh',
        id:202,
        location:'chennai',
        work:'ITjob',
        car:'Thar'
    },
    {
        name:'sailesh',
        id:202,
        location:'chennai',
        work:'ITjob',
        car:'Thar'
    },
]